spring.application.name=autoescola

server.port=8080

spring.datasource.url=jdbc:mysql://localhost/auto_escola
## todo alterar user
spring.datasource.username= root
## todo alterar senha
spring.datasource.password= senhaDeExemplo
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#server.error.include-stacktrace = never

api.security.token.secret=${JWT_TOKEN:4206769}