name: OWASP ZAP Security Scan
on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web application
    permissions:
      contents: read
      issues: write
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: test_db
          MYSQL_DATABASE: zap_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: "maven"

      - name: Rodar Spring Boot
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/zap_test
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: test_db
        run: |
          mvn clean package -DskipTests
          java -jar target/*.jar > ${{ github.workspace }}/spring.log 2>&1 &

      - name: Aguardar App subir
        run: npx wait-on http://localhost:8080/health-check --timeout 90000

      - name: Debug Logs em caso de erro
        if: failure()
        run: |
          echo "==== VERIFICANDO ARQUIVOS ===="
          ls -l
          echo "==== CONTEÚDO DO LOG ===="
          cat ${{ github.workspace }}/spring.log || echo "Log não encontrado"

      - name: Instalar jq
        run: sudo apt-get install -y jq

      - name: Obter token JWT
        run: |
          TOKEN=$(curl -s -X POST http://localhost:8080/login \
            -H "Content-Type: application/json" \
            -d '{"login":"adminLogin","senha":"admin"}' | jq -r '.token')

          echo "TOKEN=$TOKEN" >> $GITHUB_ENV

      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.13.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: "http://localhost:8080"
          fail_action: true
          cmd_options: >
            -a
            -z "
            -config replacer.full_list(0).description=auth
            -config replacer.full_list(0).enabled=true
            -config replacer.full_list(0).matchtype=REQ_HEADER
            -config replacer.full_list(0).matchstr=Authorization
            -config replacer.full_list(0).replacement=Bearer $TOKEN
            -config openapi.url=http://localhost:8080/v3/api-docs
            "

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: report_html.html

# action-full-scan@v0.13.0 - varredura profunda
# action-baseline@v0.12.0 - varredura rápida
